### ISSUE TITLE
Copper support

### ISSUE THREAD

**Issue by kauf0** [RGG200/Ascecia-Currencies#1]
Hello, I'd be great if you add copper support for your plugin.
I tried it in the config file like this: `copper_ingot: 0.6`
but it still adds 0.0 to the currency power, so I guess it's something about the core-side of the plugin.
Thank you.

**Comment by RGG200** [comment]
Thank you for your feedback. I will try to fix it as soon as possible !

**Comment by RGG200** [comment]
@kauf0 It should be fixed now on Version 1.2 Snapshot 1 !  Check it out on the spigot page or the releases page here on GitHub !
