### ISSUE TITLE
Problem with minting and Power

### ISSUE THREAD

**Issue by kauf0** [RGG200/Ascecia-Currencies#2]
Hello, thank you for yesterday's update!
Copper works now, that's great.

But now minting doesn't work with `An internal error occured`

And also I found that when server reloads power of the currency is decreased (I guess it's something about saving currency info to config). 
For example I've just added resources to 1200 power and found out I can't mint anymore, so I reloaded server and now my currency power is 350 and with my friend's currency yesterday happened the same thing.

And again, thanks for developing this plugin!

**Comment by kauf0** [comment]
Addition:
But with the Amount of Currency it stays the same as before reloading in case I both deposited resources and minted some currency. So the currency amount is the same as it was before reloading, but power is decreased like I said above.

**Comment by RGG200** [comment]
Thanks again for the feedback! I will try and fix it as soon as possible!

**Comment by RGG200** [comment]
@kauf0 Your issue is now fixed in the new version 1.2-Pre-Release 1. Check it out in spigot or GitHub ! I also tweaked with the currency power and I think it should act weird now. Also if you want I made a discord server for the plugin you can join at: https://discord.gg/n4nNd5j75U
